[project]
name = "rafale"
version = "0.0.1"
description = "opinionated transformer training cli"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "composer>=0.24.1",
    "datasets", 
    "torch>=2.4.0", # should be able to upgrade soon, composer has not yet bumped to torch 2.5.0
    "safetensors",
    "transformers>=4.44.2",
]
packages = [{include = "rafale"}]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
dev = [
    "datasets"
]
