[project]
name = "rafale"
version = "0.0.1"
description = "opinionated transformer training cli"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["torch", "composer", "datasets"]
packages = [{include = "rafale"}]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
dev = [
    "datasets"
]