[project]
name = "rafale"
version = "0.1"
description = "opinionated transformer training cli"
readme = "README.md"
requires-python = "==3.12"
packages = [{include = "rafale"}]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"